### ISSUE TITLE
What does this tool do?

### ISSUE THREAD

**Issue by deepakkumar1984** [MscrmTools/MscrmTools.PortalCodeEditor#1]
Hello,

I have Customer Self Service Portal install with Dynamics 365. Using this tool it loads the structure on left tree which is fine. After selecting the form (JS/CSS) doesn't load anything. No error no message. Not sure what is the purpose of this tool and how does it work.

**Comment by MscrmTools** [comment]
This tool helps you to edit code parts of pages and other "codable" portal items.
Page, by default, don't have any code. It's up to you to add some if you need to.
Open a template instead and you will se the code for it.
