### ISSUE TITLE
Suggestion: feature for saving files to local location

### ISSUE THREAD

**Issue by dolps** [MscrmTools/MscrmTools.PortalCodeEditor#13]
Store files locally to folder for versioncontrol

**Comment by MscrmTools** [comment]
I was thinking about this one, yes. I still need to understand how to organize the storage

**Comment by jamesnovak** [comment]
We have the same need on my current project.  
I've implemented a first pass at a solution for this, exporting the contents in a structure that matches the tree view structure.  
I can submit a pull request for the update.

**Comment by jamesnovak** [comment]
check out the latest release!
