### ISSUE TITLE
Unable to Ctrl+C Copy to clipboard in PortalCodeEditor.

### ISSUE THREAD

**Issue by JasonCare** [MscrmTools/MscrmTools.PortalCodeEditor#14]
Copying text using CTRL+C doesn't seem to copy text to clipboard. Is it possible to add the ability to do this?
CTRL+X works for cutting and I can paste with CTRL+V. 

Fantastic tool by the way.

XrmToolBox version 1.2018.4.22

Thanks,
Jason

**Comment by riclund** [comment]
@JasonCare this seems to be working for me in v1.2018.6.8 of the plugin. Are you up to date? If so, where does it happen - I'm trying it while editing a Web Template.

**Comment by JasonCare** [comment]
Just updated to the latest and its working now. 

Thanks,
Jason
