### ISSUE TITLE
Error from Metadata

### ISSUE THREAD

**Issue by Atili0** [MscrmTools/MscrmTools.PortalCodeEditor#15]
Hi i am getting this error 

Error	An error occured while loading code items: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: The entity with a name = 'adx_webpage' with namemapping = 'Logical' was not found in the MetadataCache. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=1536984, MinActiveRowVersion=1536984 (Fault Detail is equal to Exception details: 
ErrorCode: 0x80041102
Message: The entity with a name = 'adx_webpage' with namemapping = 'Logical' was not found in the MetadataCache. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=1536984, MinActiveRowVersion=1536984
TimeStamp: 2019-01-30T13:40:15.2679411Z

**Comment by MscrmTools** [comment]
You are targeting an organization that does not have portals installed

**Comment by MscrmTools** [comment]
So you might have the issue where two organizations have the same url name and unique name and you think you are connected to one org whereas your actually connected to the other one
