### ISSUE TITLE
Change Update Shortcut

### ISSUE THREAD

**Issue by aboodh95** [MscrmTools/MscrmTools.PortalCodeEditor#2]
Hi

Can you change the Update Shortcut to something near to Ctrl + S, The Ctrl + U is far to be reach in fast way without using the second hand

Thank you

**Comment by MscrmTools** [comment]
Other key than U would not mean Update... or if you have an idea of what key to use instead

**Comment by aboodh95** [comment]
Thank you

now i get used to click Ctrl + U
