### ISSUE TITLE
The entity with a name = 'adx_webpage' with namemapping = 'Logical' was not found in the MetadataCache

### ISSUE THREAD

**Issue by pramodnairm** [MscrmTools/MscrmTools.PortalCodeEditor#20]
Hi,

When I am trying to load the items using the button, I am getting the following error.
"An error occured while loading code items: The entity with a name = 'adx_webpage' with namemapping = 'Logical' was not found in the MetadataCache. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=2337585, MinActiveRowVersion=2337585"

Any help on this regard is appreciated.

I am using the latest trail blank portal.

Regards,
Pramod

**Comment by MscrmTools** [comment]
You are not targeting a cds instance with portals installed

**Comment by pramodnairm** [comment]
In the XRM toolbox connection string I am providing the CRM instance url. Is that not right?

**Comment by MscrmTools** [comment]
I guess it’s not the appropriate one. This error message happens only if the entity adx_webpage is not on the target cds instance.
To ensure that, open metadata browser tool and check if portals entity are present
