### ISSUE TITLE
Search starts after single character input

### ISSUE THREAD

**Issue by tenholder** [MscrmTools/MscrmTools.PortalCodeEditor#22]
The Search box initiates searching after the first character is entered.
This may be fine in small applications but in an application with a 1000 objects it becomes hard to type the whole word you want to search.
I might suggest a button to initiate the search once the full string has been entered, or start 1 or 2 seconds after typing stops.

Thanks

**Comment by MscrmTools** [comment]
I will add a pause of few milliseconds to cancel the process of search. Already tested, it allows to type text without being interrupt by the search
