### ISSUE TITLE
Search content does not work for web pages

### ISSUE THREAD

**Issue by partridgetim** [MscrmTools/MscrmTools.PortalCodeEditor#25]
The search content (not the search name) feature does not seem to work for web pages.

![image](https://user-images.githubusercontent.com/3292237/126505568-822baf79-c784-4263-b152-081f14b4e347.png)

**Comment by MscrmTools** [comment]
Hi @partridgetim! Thank you for reporting this.
I will check the code

**Comment by MscrmTools** [comment]
Very lately, I checked and found latest version works well
