### ISSUE TITLE
Web pages not editable

### ISSUE THREAD

**Issue by olabm10** [MscrmTools/MscrmTools.PortalCodeEditor#26]
Web pages cant be expanded to editing javascript/css/content. When i click on any of the web existing pages, or create a new, nothing happens.

My guess is that this has to do with the language in which the portal has been created with. (Norwegian instead of english)

**Comment by MscrmTools** [comment]
Hi @olabm10, 

Can you share a screenshot?

I have the same kind of config (with a French portal) and it works
![image](https://user-images.githubusercontent.com/10774317/149769899-51b043fa-063c-43aa-859d-64a63f2a2a3f.png)

**Comment by MscrmTools** [comment]
@olabm10 do you still have this issue?
