### ISSUE TITLE
Unable to load items

### ISSUE THREAD

**Issue by CarlosZaldivar** [MscrmTools/MscrmTools.PortalCodeEditor#3]
When trying to load items I get this error:

`An error occured while loading code items: The entity with a name = 'adx_webpage' with namemapping = 'Logical' was not found in the MetadataCache. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=1368082, MinActiveRowVersion=1368082`

I have trial Dynamics instance with version 9.0.0.3292

**Comment by CarlosZaldivar** [comment]
Never mind, my bad :)

**Comment by singhne07** [comment]
Iam getting the same issue. Were you able to solve it. Would you please help me out of this

**Comment by CarlosZaldivar** [comment]
I don't remember now what exactly I was trying to do but it turned out that I just misunderstood what this tool does and I don't really need it.
