### ISSUE TITLE
Portal code editor Steps are not categorized per Form which the old version had.

### ISSUE THREAD

**Issue by MscrmTools** [MscrmTools/MscrmTools.PortalCodeEditor#31]
See [Issue #1307](https://github.com/MscrmTools/XrmToolBox/issues/1307)

**Comment by MscrmTools** [comment]
@richardmadlansacay can you test if this version fixes the issue:

[MscrmTools.PortalCodeEditor.zip](https://github.com/MscrmTools/MscrmTools.PortalCodeEditor/files/13633496/MscrmTools.PortalCodeEditor.zip)

**Comment by richardmadlansacay** [comment]
Hi,

Where should I copy  the dll?

**Comment by MscrmTools** [comment]
In your XrmToolBox Plugins folder. If you don't know where that is, go to settings, Paths, then click on Open XrmToolBox storage folder.
The file should go there but you will be able to copy it only when XrmToolBox is closed

**Comment by richardmadlansacay** [comment]
Copied it but got this error.

![image](https://github.com/MscrmTools/MscrmTools.PortalCodeEditor/assets/83061610/d7c730c0-40ef-4b8c-bfab-9a77f5847c0f)

**Comment by MscrmTools** [comment]
@richardmadlansacay sorry, my bad.
Can you try with this one?
[MscrmTools.PortalCodeEditor.zip](https://github.com/MscrmTools/MscrmTools.PortalCodeEditor/files/13645521/MscrmTools.PortalCodeEditor.zip)

**Comment by richardmadlansacay** [comment]
Perfect! Thanks!

![image](https://github.com/MscrmTools/MscrmTools.PortalCodeEditor/assets/83061610/8741f607-e3c2-4a65-8dac-fdf08d7c286a)
