### ISSUE TITLE
I can't move webfiles due to error with business unit id error

### ISSUE THREAD

**Issue by baraveze** [MscrmTools/MscrmTools.PortalCodeEditor#32]
I tried to move power pages portal from dev environment to test environment and I get this error: "Entity 'businessunit' With Id = 745e195c-eae0-ec11-bb3d-000d3a8ea0b5 Does Not Exist". 

First, I don't have the chance to map in anyway that information from source to target. Then it's expected that GUID between different environments don't be the same. Isn't the tool searching parent records by name?. For example, Business units have the same exactly name between dev and test.

I have the same issue with lot of other entities as well. 

Any help on this? Thanks!

**Comment by MscrmTools** [comment]
Hi @baraveze 

I don't understand what you mean by trying to "move" portal. Portal Code Editor is not meant to handle data transport between environment...

**Comment by baraveze** [comment]
Sorry, disregard my message. I got the wrong github project.
