### ISSUE TITLE
Plans for further improvements?

### ISSUE THREAD

**Issue by riclund** [MscrmTools/MscrmTools.PortalCodeEditor#4]
What plans are there for making this better? Having just discovered it I'm loving the fact that it cuts the config time massively vs flipping in and out of views and records in CRM itself. I do notice one or two oddities and improvements that could be made though.

**Comment by MscrmTools** [comment]
Please create an issue for each bug or improvements so that I can track them.

**Comment by riclund** [comment]
Will do. I'll get to a PC where I can get some useful screenshots tomorrow. Thanks.

Any other plans for improvements and can you confirm this will continue to support all three versions of portals - Online, Community and legacy ADX?

**Comment by MscrmTools** [comment]
Next major improvement would be to use dockpanelsuite to allow same kind of visual studio windows organization.

And, yes, it will continue to support the three portal versions

**Comment by riclund** [comment]
Cool, sounds good. I'll be happy to provide input and help if needed - this is quite a time saver!
