### ISSUE TITLE
Unable to cast object of type 'System.Windows.Forms.MdiClient' to type 'System.Windows.Forms.TabControl'.

### ISSUE THREAD

**Issue by yogeshvc** [MscrmTools/MscrmTools.PortalCodeEditor#7]
In latest version of XrmToolbox(v 1.2018.3.21) when I open any EntityForms' Javascript code and hit Ctrl + F, I get following error.

Unable to cast object of type 'System.Windows.Forms.MdiClient' to type 'System.Windows.Forms.TabControl'

Is this known issue, if it is then could you please suggest any work around?

Thank you,

**Comment by MscrmTools** [comment]
I will try to provide a fix ASAP, sorry for that

**Comment by MscrmTools** [comment]
I cannot do faster :)

Just let me publish a new package, wait for its indexing, then you should be able to download the update and work like before

**Comment by yogeshvc** [comment]
Thank you for fixing it so quickly, however I am having another problem. I cannot use Ctrl+C, its not copying to clipboard but I can paste whatever it in clipboard. I have explicitly right click and click Copy to do what I need to do. Its not urgent, so you can take your time on that one...

**Comment by MscrmTools** [comment]
Arf... I was too fast! I plan to rebuilt the whole plugin to use DockPanel like XrmToolBox so the fix will be included
